language: node_js
node_js:
  - "0.10.40"
env:
  global:
     - BROWSERSTACK_USERNAME=heejaekim1
     - BROWSERSTACK_KEY=qzhCCRaTygGqQwLNm6mu
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
addons:
    code_climate:
        repo_token: cf535674171f2bece5fbdc51d09bafc4f5691ff34a2b03a5e9443e0d0b9477e4
